name: pvr_ccz
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com
repository: https://github.com/bung87/pvr-ccz
issue_tracker: https://github.com/bung87/pvr-ccz/issues

environment:
  sdk: '>=2.0.0-dev.49.0 <3.0.0'

dependencies:
 path: ^1.6.0
 image:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
